dubbo:
  config-center:
    address: zookeeper://zookeeper:2181
  registry:
    address: zookeeper://zookeeper:2181
    timeout: 30000
  metadata-report:
    address: zookeeper://zookeeper:2181
    timeout: 30000

spring:
  redis:
    url: redis://host.docker.internal:6379
  profiles:
    active: test
cake:
  sso:
    redis:
      address: redis://127.0.0.1:6379


