server:
  port: 8300

logging:
  file:
    path: /home/admin/cake-dingtalk-sso-server/logs

dubbo:
  application:
    id: cake-dingtalk-sso-service
    name: cake-dingtalk-sso-service
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  registry:
    protocol: zookeeper
    id: my-registry
  scan:
    basePackages: com.rany.cake.dingtalk

spring:
  profiles:
    active: dev
  application:
    name: cake-dingtalk-sso-server
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false




dingtalk:
  agentId: ###
  appKey: ###
  appSecret: ###
  corpId: ###

cake:
  uic:
    # #需要替换为cake-ops内的某一个租户
    tenantId: 768460649511661568