dubbo:
  config-center:
    address: zookeeper://zookeeper.default.svc.cluster.local:2181
    timeout: 30000
  registry:
    address: zookeeper://zookeeper.default.svc.cluster.local:2181
    timeout: 30000
  metadata-report:
    address: zookeeper://zookeeper.default.svc.cluster.local:2181
    timeout: 30000

spring:
  redis:
    url: redis://redis.default.svc.cluster.local:6379
cake:
  sso:
    redis:
      address: redis://redis.default.svc.cluster.local:6379


easy:
  sso:
    server:
      maxAge: 7200
    client:
      enable: true
      client-type: web
      sso-server: http://test.sso.rany.com/
      login-url: http://test.sso.rany.com/sso/loginPage
      logout-url: /sso/logout
      ignore-urls: /ok,/sso/loginPage,/sso/login,/sso/code,/swagger-resources/**,/v2/api-docs
      ignore-resources: .js, .css, .jpg, .png, .ico, .html
      ajax-failure-response:
        code: 401
        msg: 用户未登录
        content-type: application/json
    redis:
      address: redis://redis.default.svc.cluster.local:6379

