dubbo:
  config-center:
    address: zookeeper://zookeeper.default.svc.cluster.local:2181
    timeout: 30000
  registry:
    address: zookeeper://zookeeper.default.svc.cluster.local:2181
    timeout: 30000
  metadata-report:
    address: zookeeper://zookeeper.default.svc.cluster.local:2181
    timeout: 30000

spring:
  redis:
    url: redis://redis.default.svc.cluster.local:6379
  profiles:
    active: test
cake:
  sso:
    redis:
      address: redis://redis.default.svc.cluster.local:6379


