server:
  port: 8765
  tomcat:
    connection-timeout: 18000000
logging:
  file:
    path: /Users/yuanjinxiu/cake-dingtalk-sso-server/logs

dubbo:
  config-center:
    address: zookeeper://127.0.0.1:2181
  registry:
    address: zookeeper://127.0.0.1:2181
    client: curator
  metadata-report:
    address: zookeeper://127.0.0.1:2181

spring:
  redis:
    url: redis://127.0.0.1:6379
cake:
  sso:
    redis:
      address: redis://127.0.0.1:6379

# 开启swagger
swagger:
  enabled: true

easy:
  sso:
    server:
      maxAge: 7200
    client:
      enable: true
      client-type: web
      sso-server: http://127.0.0.1:8765/
      login-url: http://127.0.0.1:8765/sso/loginPage
      logout-url: /sso/logout
      ignore-urls: /ok,/sso/loginPage,/sso/login,/sso/code,/swagger-resources/**,/v2/api-docs
      ignore-resources: .js, .css, .jpg, .png, .ico, .html
      ajax-failure-response:
        code: 401
        msg: 用户未登录
        content-type: application/json
    redis:
      address: redis://127.0.0.1:6379