server:
  port: 8300

logging:
  file:
    path: /home/admin/cake-dingtalk-sso-server/logs

dubbo:
  application:
    id: cake-dingtalk-sso-service
    name: cake-dingtalk-sso-service
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  registry:
    protocol: zookeeper
    id: my-registry
    address: 127.0.0.1:2181
  scan:
    basePackages: com.rany.cake.dingtalk

spring:
  application:
    name: cake-dingtalk-sso-server
  mvc:
    favicon:
      enabled: false
  redis:
    url: redis://127.0.0.1:6379
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false




dingtalk:
  agentId: 1264202242
  appKey: dingdmo8khbuyyvgvcmi
  appSecret: Gi1Aa8FKdUo28P1NNa5weWZKN3v8i_q9AcXCZ6oAnDOA-CElLhZJZNzR0Ig1OQnk
  corpId: ding3f7cf4e7c622e7eb4ac5d6980864d335

cake:
  uic:
    tenantId: 768460649511661568